config/routes.rb
CaptainsLog::Application.routes.draw do
  get "landing_pages/home" 
  get "landing_pages/about"
  get "landing_pages/signup"

  root :to => "landing_pages#home"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController

  layout "application"

  def home
  end

  def signup
  	landing_pages_signup_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/landing_pages/about.html.erb
<head>
</head>

<body>

	<div class="top_box">
				<img src='<%=asset_path "home_banner_4generations.jpg" %>'>
			<div id="top_box_text">
				<h1>Captain's Log</h1>
			</div>
	</div>

	<div id="about_box">
		<h2>We'd love to hear from you</h2>
	</br>
		<p>A bit about us. We're like you more or less. We've had a lot of serious thoughts, dramatic experiences, big decisions, ambitious visions, grand ideas, sad reflections. That's what makes life worth living. But we realized, we forget a lot of those details.</p>
		<p>That's normal of course, we're human. But it doesn't have to be that way. We want to live in a world where your family members can pass on logs to share parts of their journey with you. And where your logs will live on as a legacy that's more human than a statue or name on a building.</p>
		<p>Can you imagine that? We hope to help make it happen.</p>
	</br>
		<p><strong>We'd love to hear any thoughts:</strong> new.captains.log[at]gmail</p>
	</div>

	<footer>
		<div id="footer" style="position:absolute; margin-top: 320px; left:50%; margin-left: -130px;"> 
			<p>© 2014 <%= link_to "Captain's Log", landing_pages_home_path %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to "About", landing_pages_about_path %>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="mailto:a friend or family">Share</a></p>
	</footer>


</body>

app/views/landing_pages/home.html.erb
<!DOCTYPE html>
<head>


</head>

<body>
	<div class="top_box">
			<img src='<%=asset_path "home_banner_4generations.jpg" %>'>
		<div id="top_box_text">
			<h1>Captain's Log</h1>
			<h2>What if Oprah interviewed you, so you don't have to keep a journal.</h2>
		</div>
	</div>
	<a href="#middle_headline">
		<div id="top_center_image">
				<img src='<%=asset_path "HuntersRecording.png" %>'>
		</div>
	</a>
	<a href="#middle_headline" data-scroll data-speed="1000" data-easing="easeInOutCubic" data-url="false">
		<div id="top_arrow">
			<img src='<%=asset_path "down_arrow.png" %>'>
		</div>
	</a>	
	<div class="container bottom_box">
		<div class="row">
			<div class="middle col-md-12">
				<div id="middle_headline">
					<h2>Life is about the journey. But we forget the details.</h2>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="left col-md-6">
				<div id="details">
					<div id="details_two">
						<p><span>How it works —</span> You and the professional interviewer sign an NDA. Then you pick a time to set aside 60 minutes to video chat. She'll introduce herself and ask about what's on your mind. Aftward, you'll get sent the recording. That's it! You can do it once or twice a year.</p>
					</br>
				</br>
					</br>
					</div>
					<div id="details_one">
						<p>Why do it —<span> We spend all this time and energy thinking about things: your first boss, your next job, a girl or boy you're into, your family, your goals, why the world is the way it is. We obsess over these things, but then we forget it all. Do you remember what you were thinking when you were a freshman in college? Before your first kiss? When you started your first job? Many of us wish we kept a journal, but it's hard and doesn't capture your body language. Captains Log is easy. You'll be able to revisit your past self, share it with family, or even erase it.</span></p>
					</div>
				</div>
			</div>
			<div class="center_line">
			</div>
			<div class="right col-md-6">
				<div id="signup">
					<h1>Start your Captain's Log</h1>
					<%= link_to "NEW CAPTAIN'S LOG", landing_pages_signup_path, :style => "width:300px; padding: 20px 0px; id:signup_btn", :class => "btn btn-success btn-lg" %>
					<p id="signup_para">It's harder than a selfie. But easier than a journal. And better than forgetting the journey. Try it.</p>
				</div>
			</div>
		</div>
	</div>
	<footer>
		<div id="footer"> 
			<p>© 2014 <%= link_to "Captain's Log", landing_pages_home_path %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to "About", landing_pages_about_path %>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="mailto:a friend or family">Share</a></p>
	</footer>

	<script src="https://www.dropbox.com/s/1jndd0xds0f3z6o/smooth-scroll.js"></script>
</body>

app/views/landing_pages/signup.html.erb
<head>

	<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
	<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif;  width:300px;}
	
	</style>

		<!-- Facebook Conversion Code for fb_right_promo -->
<script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6017760030131';
fb_param.value = '0.00';
fb_param.currency = 'USD';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>

<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6017760030131&amp;value=0&amp;currency=USD" /></noscript>

</head>

<body>

	<div class="top_box">
			<img src='<%=asset_path "home_banner_4generations.jpg" %>'>
		<div id="top_box_text">
			<h1>Captain's Log</h1>
		</div>
	</div>
	<div id="signup_page_box">
		<div id="mc_embed_signup">
			<div id="top">
			<h2 style="text-align:center">We're not accepting new members</br>at the moment.</h2>
			<p>We're so happy you're going to do a Captain's Log! We want things to be perfect when you do it and we have a few more things to hammer out. Hope you'll join the waitlist: we'll let you know when it's ready.</p>
		</br>
		<h1 style="color:#43994D">Join the waitlist</h1>
		<form action="http://newcaptainslog.us3.list-manage.com/subscribe/post?u=f696bef6da9c8b8f31cbd1c6f&amp;id=40ef2656e5" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
		<div class="mc-field-group input-group">
		    <strong>Which would you prefer?</strong>
		    <ul>
		    	<li><input type="radio" value="First Choice" name="MMERGE4" id="mce-MMERGE4-0"><label for="mce-MMERGE4-0">  Computer-generated prompts</label></li>
				<li><input type="radio" value="Second Choice" name="MMERGE4" id="mce-MMERGE4-1"><label for="mce-MMERGE4-1">  Professional interviewer (annonymously)</label></li>
			</ul>
		</div>
		<div class="mc-field-group">
			<label for="mce-EMAIL">Email  <span class="asterisk">*</span>
		</label>
			<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
		</div>
		<div class="mc-field-group">
			<label for="mce-FNAME">First Name </label>
			<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
		</div>
		<div class="mc-field-group size1of2">
			<label for="mce-MMERGE2">Age </label>
			<input type="number" name="MMERGE2" class="" value="" id="mce-MMERGE2">
		</div>
			<div id="mce-responses" class="clear">
				<div class="response" id="mce-error-response" style="display:none"></div>
				<div class="response" id="mce-success-response" style="display:none"></div>
			</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
		    <div style="position: absolute; left: -5000px;"><input type="text" name="b_f696bef6da9c8b8f31cbd1c6f_40ef2656e5" value=""></div>
			<div class="clear" style="margin: 80px 0px 50px;"><input type="submit" value="Submit" name="subscribe" id="mc-embedded-subscribe" class="btn-success" style="border-color:#43994D; width:200px; height: 40px; margin-left: 0px; border-radius:2px;"></div>
		</form>
		</div>
	</div>
	<footer>
		<div id="footer" style="position:absolute; margin-top: 600px; left:50%; margin-left: -130px;"> 
			<p>© 2014 <%= link_to "Captain's Log", landing_pages_home_path %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to "About", landing_pages_about_path %>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="mailto:a friend or family">Share</a></p>
	</footer>









	<script type="text/javascript">
	var fnames = new Array();var ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='MMERGE2';ftypes[2]='number';fnames[3]='MMERGE3';ftypes[3]='dropdown';fnames[4]='MMERGE4';ftypes[4]='radio';
	try {
	    var jqueryLoaded=jQuery;
	    jqueryLoaded=true;
	} catch(err) {
	    var jqueryLoaded=false;
	}
	var head= document.getElementsByTagName('head')[0];
	if (!jqueryLoaded) {
	    var script = document.createElement('script');
	    script.type = 'text/javascript';
	    script.src = '//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js';
	    head.appendChild(script);
	    if (script.readyState && script.onload!==null){
	        script.onreadystatechange= function () {
	              if (this.readyState == 'complete') mce_preload_check();
	        }    
	    }
	}

	var err_style = '';
	try{
	    err_style = mc_custom_error_style;
	} catch(e){
	    err_style = '#mc_embed_signup input.mce_inline_error{border-color:#6B0505;} #mc_embed_signup div.mce_inline_error{margin: 0 0 1em 0; padding: 5px 10px; background-color:#6B0505; font-weight: bold; z-index: 1; color:#fff;}';
	}
	var head= document.getElementsByTagName('head')[0];
	var style= document.createElement('style');
	style.type= 'text/css';
	if (style.styleSheet) {
	  style.styleSheet.cssText = err_style;
	} else {
	  style.appendChild(document.createTextNode(err_style));
	}
	head.appendChild(style);
	setTimeout('mce_preload_check();', 250);

	var mce_preload_checks = 0;
	function mce_preload_check(){
	    if (mce_preload_checks>40) return;
	    mce_preload_checks++;
	    try {
	        var jqueryLoaded=jQuery;
	    } catch(err) {
	        setTimeout('mce_preload_check();', 250);
	        return;
	    }
	    var script = document.createElement('script');
	    script.type = 'text/javascript';
	    script.src = 'http://downloads.mailchimp.com/js/jquery.form-n-validate.js';
	    head.appendChild(script);
	    try {
	        var validatorLoaded=jQuery("#fake-form").validate({});
	    } catch(err) {
	        setTimeout('mce_preload_check();', 250);
	        return;
	    }
	    mce_init_form();
	}
	function mce_init_form(){
	    jQuery(document).ready( function($) {
	      var options = { errorClass: 'mce_inline_error', errorElement: 'div', onkeyup: function(){}, onfocusout:function(){}, onblur:function(){}  };
	      var mce_validator = $("#mc-embedded-subscribe-form").validate(options);
	      $("#mc-embedded-subscribe-form").unbind('submit');//remove the validator so we can get into beforeSubmit on the ajaxform, which then calls the validator
	      options = { url: 'http://newcaptainslog.us3.list-manage.com/subscribe/post-json?u=f696bef6da9c8b8f31cbd1c6f&id=40ef2656e5&c=?', type: 'GET', dataType: 'json', contentType: "application/json; charset=utf-8",
	                    beforeSubmit: function(){
	                        $('#mce_tmp_error_msg').remove();
	                        $('.datefield','#mc_embed_signup').each(
	                            function(){
	                                var txt = 'filled';
	                                var fields = new Array();
	                                var i = 0;
	                                $(':text', this).each(
	                                    function(){
	                                        fields[i] = this;
	                                        i++;
	                                    });
	                                $(':hidden', this).each(
	                                    function(){
	                                        var bday = false;
	                                        if (fields.length == 2){
	                                            bday = true;
	                                            fields[2] = {'value':1970};//trick birthdays into having years
	                                        }
	                                    	if ( fields[0].value=='MM' && fields[1].value=='DD' && (fields[2].value=='YYYY' || (bday && fields[2].value==1970) ) ){
	                                    		this.value = '';
										    } else if ( fields[0].value=='' && fields[1].value=='' && (fields[2].value=='' || (bday && fields[2].value==1970) ) ){
	                                    		this.value = '';
										    } else {
										        if (/\[day\]/.test(fields[0].name)){
	    	                                        this.value = fields[1].value+'/'+fields[0].value+'/'+fields[2].value;									        
										        } else {
	    	                                        this.value = fields[0].value+'/'+fields[1].value+'/'+fields[2].value;
		                                        }
		                                    }
	                                    });
	                            });
	                        $('.phonefield-us','#mc_embed_signup').each(
	                            function(){
	                                var fields = new Array();
	                                var i = 0;
	                                $(':text', this).each(
	                                    function(){
	                                        fields[i] = this;
	                                        i++;
	                                    });
	                                $(':hidden', this).each(
	                                    function(){
	                                        if ( fields[0].value.length != 3 || fields[1].value.length!=3 || fields[2].value.length!=4 ){
	                                    		this.value = '';
										    } else {
										        this.value = 'filled';
		                                    }
	                                    });
	                            });
	                        return mce_validator.form();
	                    }, 
	                    success: mce_success_cb
	                };
	      $('#mc-embedded-subscribe-form').ajaxForm(options);
	      
	      
	    });
	}
	function mce_success_cb(resp){
	    $('#mce-success-response').hide();
	    $('#mce-error-response').hide();
	    if (resp.result=="success"){
	        $('#mce-'+resp.result+'-response').show();
	        $('#mce-'+resp.result+'-response').html(resp.msg);
	        $('#mc-embedded-subscribe-form').each(function(){
	            this.reset();
	    	});
	    } else {
	        var index = -1;
	        var msg;
	        try {
	            var parts = resp.msg.split(' - ',2);
	            if (parts[1]==undefined){
	                msg = resp.msg;
	            } else {
	                i = parseInt(parts[0]);
	                if (i.toString() == parts[0]){
	                    index = parts[0];
	                    msg = parts[1];
	                } else {
	                    index = -1;
	                    msg = resp.msg;
	                }
	            }
	        } catch(e){
	            index = -1;
	            msg = resp.msg;
	        }
	        try{
	            if (index== -1){
	                $('#mce-'+resp.result+'-response').show();
	                $('#mce-'+resp.result+'-response').html(msg);            
	            } else {
	                err_id = 'mce_tmp_error_msg';
	                html = '<div id="'+err_id+'" style="'+err_style+'"> '+msg+'</div>';
	                
	                var input_id = '#mc_embed_signup';
	                var f = $(input_id);
	                if (ftypes[index]=='address'){
	                    input_id = '#mce-'+fnames[index]+'-addr1';
	                    f = $(input_id).parent().parent().get(0);
	                } else if (ftypes[index]=='date'){
	                    input_id = '#mce-'+fnames[index]+'-month';
	                    f = $(input_id).parent().parent().get(0);
	                } else {
	                    input_id = '#mce-'+fnames[index];
	                    f = $().parent(input_id).get(0);
	                }
	                if (f){
	                    $(f).append(html);
	                    $(input_id).focus();
	                } else {
	                    $('#mce-'+resp.result+'-response').show();
	                    $('#mce-'+resp.result+'-response').html(msg);
	                }
	            }
	        } catch(e){
	            $('#mce-'+resp.result+'-response').show();
	            $('#mce-'+resp.result+'-response').html(msg);
	        }
	    }
	}
	</script>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <title>Captain's Log</title>

  <link rel="stylesheet" type="text/css" 
   href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

<%= yield %>

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://code.jquery.com/jquery.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="js/bootstrap.min.js"></script>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48296375-1', 'newcaptainslog.com');
  ga('send', 'pageview');

</script>
</body>
</html>